In [206]:
import pandas as pd
import numpy as np

In [207]:
df = pd.read_csv('Bioenergy_generation.csv', sep=';',decimal=',', header=None)

In [208]:
df

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Country,2000.00,2001.00,2002.00,2003.00,2004.00,2005.00,2006.00,2007.00,2008.00,...,2012.00,2013.00,2014.00,2015.00,2016.00,2017.00,2018.00,2019.00,2020.00,2021.00
1,Albania,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60
11,Estonia,0.01,0.01,0.02,0.03,0.03,0.04,0.04,0.03,0.04,...,1.00,0.67,0.76,0.82,0.95,1.10,1.31,1.36,1.35,1.25
12,Finland,8.64,8.27,8.99,9.38,10.44,9.51,10.81,9.95,10.40,...,11.20,12.01,11.76,11.42,11.52,11.86,12.91,13.29,11.08,12.28
13,France,2.48,2.85,3.04,3.23,3.31,3.39,3.38,3.75,3.97,...,5.30,5.68,5.99,6.53,7.52,7.78,8.38,8.64,8.47,8.67
14,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
15,Germany,4.33,4.59,5.31,8.95,10.64,14.71,18.94,24.62,28.02,...,43.20,45.51,48.29,50.33,50.93,50.92,50.90,50.22,49.27,48.99
16,Greece,0.00,0.08,0.13,0.10,0.12,0.12,0.11,0.18,0.19,...,0.20,0.22,0.22,0.23,0.27,0.31,0.31,0.40,0.40,0.40
17,Hungary,0.06,0.07,0.04,0.16,0.73,1.66,1.26,1.56,1.94,...,1.65,1.83,2.13,2.16,2.07,2.15,2.30,2.22,2.27,2.37
18,Iceland,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
19,Ireland,0.09,0.10,0.08,0.09,0.11,0.13,0.13,0.18,0.22,...,0.44,0.49,0.54,0.48,0.68,0.74,0.85,0.85,0.85,0.85
20,Italy,1.39,1.83,2.71,3.37,4.22,4.67,5.11,5.26,5.97,...,12.49,17.08,18.72,19.39,19.50,19.37,19.14,19.55,19.58,19.83
21,Latvia,0.00,0.00,0.01,0.02,0.04,0.04,0.04,0.04,0.04,...,0.29,0.50,0.67,0.77,0.82,0.93,0.94,0.93,0.87,0.86
22,Lithuania,0.00,0.00,0.00,0.01,0.01,0.01,0.02,0.05,0.07,...,0.22,0.36,0.40,0.45,0.44,0.50,0.54,0.53,0.52,0.51
23,Luxembourg,0.02,0.03,0.03,0.03,0.04,0.05,0.06,0.06,0.07,...,0.09,0.09,0.12,0.13,0.14,0.17,0.22,0.28,0.36,0.38
24,Malta,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
25,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.01,0.01,0.01,0.02,0.03,0.03,NaN,NaN
26,Montenegro,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
27,Netherlands,1.99,2.35,2.90,2.54,3.31,5.26,5.17,4.00,5.13,...,7.20,5.95,5.01,4.92,4.90,4.60,4.57,5.81,8.65,11.65
28,North Macedonia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.02,0.04,0.05,0.05,0.06,0.06,0.06
29,Norway,0.26,0.25,0.25,0.33,0.36,0.33,0.39,0.39,0.40,...,0.33,0.40,0.26,0.26,0.23,0.26,0.20,0.25,0.25,0.25
30,Poland,0.22,0.44,0.43,0.46,0.98,1.51,1.99,2.56,3.62,...,10.09,8.62,9.98,9.94,7.96,6.49,6.55,7.68,7.70,7.53
31,Portugal,1.30,1.35,1.47,1.39,1.54,1.68,1.70,1.86,1.85,...,2.95,3.05,3.05,3.10,3.07,3.22,3.16,3.36,3.91,3.92
32,Romania,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.04,0.02,...,0.21,0.25,0.50,0.52,0.53,0.53,0.44,0.50,0.58,0.65
33,Serbia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.01,0.02,0.02,0.02,0.03,0.08,0.10,0.14,0.16,0.28
34,Slovakia,0.00,0.15,0.15,0.10,0.02,0.03,0.40,0.47,0.52,...,0.94,0.91,1.42,1.66,1.73,1.70,1.63,1.69,1.77,1.76
35,Slovenia,0.07,0.07,0.10,0.12,0.12,0.11,0.11,0.11,0.29,...,0.27,0.26,0.25,0.26,0.28,0.28,0.26,0.25,0.26,0.20
36,Spain,1.49,1.63,2.59,3.18,3.33,2.65,2.77,2.90,3.26,...,4.98,5.80,5.41,5.76,5.69,6.08,5.91,5.57,6.49,6.80
37,Sweden,4.10,3.78,4.18,4.51,7.20,7.49,8.36,9.84,10.34,...,12.19,11.45,10.70,10.77,11.49,12.08,11.91,13.04,10.84,12.99
38,Turkey,0.17,0.18,0.13,0.08,0.08,0.03,0.06,0.09,0.14,...,0.59,0.88,1.08,1.24,1.63,2.10,2.65,3.51,4.42,6.26
39,Ukraine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.26,...,0.13,0.10,0.13,0.14,0.14,0.21,0.30,0.41,NaN,NaN
40,United Kingdom,3.94,4.53,5.08,6.10,7.36,9.10,9.28,9.33,9.57,...,14.73,18.10,22.62,28.47,30.06,31.87,34.93,37.29,38.10,39.10

In [209]:
first_20=df.head(20)
first_20

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,Country,2000.00,2001.00,2002.00,2003.00,2004.00,2005.00,2006.00,2007.00,2008.00,...,2012.00,2013.00,2014.00,2015.00,2016.00,2017.00,2018.00,2019.00,2020.00,2021.00
1,Albania,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60
11,Estonia,0.01,0.01,0.02,0.03,0.03,0.04,0.04,0.03,0.04,...,1.00,0.67,0.76,0.82,0.95,1.10,1.31,1.36,1.35,1.25
12,Finland,8.64,8.27,8.99,9.38,10.44,9.51,10.81,9.95,10.40,...,11.20,12.01,11.76,11.42,11.52,11.86,12.91,13.29,11.08,12.28
13,France,2.48,2.85,3.04,3.23,3.31,3.39,3.38,3.75,3.97,...,5.30,5.68,5.99,6.53,7.52,7.78,8.38,8.64,8.47,8.67
14,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
15,Germany,4.33,4.59,5.31,8.95,10.64,14.71,18.94,24.62,28.02,...,43.20,45.51,48.29,50.33,50.93,50.92,50.90,50.22,49.27,48.99
16,Greece,0.00,0.08,0.13,0.10,0.12,0.12,0.11,0.18,0.19,...,0.20,0.22,0.22,0.23,0.27,0.31,0.31,0.40,0.40,0.40
17,Hungary,0.06,0.07,0.04,0.16,0.73,1.66,1.26,1.56,1.94,...,1.65,1.83,2.13,2.16,2.07,2.15,2.30,2.22,2.27,2.37
18,Iceland,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
19,Ireland,0.09,0.10,0.08,0.09,0.11,0.13,0.13,0.18,0.22,...,0.44,0.49,0.54,0.48,0.68,0.74,0.85,0.85,0.85,0.85

In [210]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22],
           dtype='int64')

In [211]:
df.rename(columns = {0:'Country'}, inplace = True)

In [212]:
df.columns

Index(['Country',         1,         2,         3,         4,         5,
               6,         7,         8,         9,        10,        11,
              12,        13,        14,        15,        16,        17,
              18,        19,        20,        21,        22],
      dtype='object')

In [213]:
for i in range(1,23):
    df.rename(columns={i:str(2000+i-1)},inplace = True)

In [214]:
df.columns

Index(['Country', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [215]:
# after changing columns name
df= df.drop(labels=0)
first_20=df.head(20)
first_20

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Albania,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60
11,Estonia,0.01,0.01,0.02,0.03,0.03,0.04,0.04,0.03,0.04,...,1.00,0.67,0.76,0.82,0.95,1.10,1.31,1.36,1.35,1.25
12,Finland,8.64,8.27,8.99,9.38,10.44,9.51,10.81,9.95,10.40,...,11.20,12.01,11.76,11.42,11.52,11.86,12.91,13.29,11.08,12.28
13,France,2.48,2.85,3.04,3.23,3.31,3.39,3.38,3.75,3.97,...,5.30,5.68,5.99,6.53,7.52,7.78,8.38,8.64,8.47,8.67
14,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
15,Germany,4.33,4.59,5.31,8.95,10.64,14.71,18.94,24.62,28.02,...,43.20,45.51,48.29,50.33,50.93,50.92,50.90,50.22,49.27,48.99
16,Greece,0.00,0.08,0.13,0.10,0.12,0.12,0.11,0.18,0.19,...,0.20,0.22,0.22,0.23,0.27,0.31,0.31,0.40,0.40,0.40
17,Hungary,0.06,0.07,0.04,0.16,0.73,1.66,1.26,1.56,1.94,...,1.65,1.83,2.13,2.16,2.07,2.15,2.30,2.22,2.27,2.37
18,Iceland,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
19,Ireland,0.09,0.10,0.08,0.09,0.11,0.13,0.13,0.18,0.22,...,0.44,0.49,0.54,0.48,0.68,0.74,0.85,0.85,0.85,0.85
20,Italy,1.39,1.83,2.71,3.37,4.22,4.67,5.11,5.26,5.97,...,12.49,17.08,18.72,19.39,19.50,19.37,19.14,19.55,19.58,19.83

In [216]:
df.index

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
            35, 36, 37, 38, 39, 40],
           dtype='int64')

In [217]:
df.sort_values('Country')

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Albania,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60
11,Estonia,0.01,0.01,0.02,0.03,0.03,0.04,0.04,0.03,0.04,...,1.00,0.67,0.76,0.82,0.95,1.10,1.31,1.36,1.35,1.25
12,Finland,8.64,8.27,8.99,9.38,10.44,9.51,10.81,9.95,10.40,...,11.20,12.01,11.76,11.42,11.52,11.86,12.91,13.29,11.08,12.28
13,France,2.48,2.85,3.04,3.23,3.31,3.39,3.38,3.75,3.97,...,5.30,5.68,5.99,6.53,7.52,7.78,8.38,8.64,8.47,8.67
14,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
15,Germany,4.33,4.59,5.31,8.95,10.64,14.71,18.94,24.62,28.02,...,43.20,45.51,48.29,50.33,50.93,50.92,50.90,50.22,49.27,48.99
16,Greece,0.00,0.08,0.13,0.10,0.12,0.12,0.11,0.18,0.19,...,0.20,0.22,0.22,0.23,0.27,0.31,0.31,0.40,0.40,0.40
17,Hungary,0.06,0.07,0.04,0.16,0.73,1.66,1.26,1.56,1.94,...,1.65,1.83,2.13,2.16,2.07,2.15,2.30,2.22,2.27,2.37
18,Iceland,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
19,Ireland,0.09,0.10,0.08,0.09,0.11,0.13,0.13,0.18,0.22,...,0.44,0.49,0.54,0.48,0.68,0.74,0.85,0.85,0.85,0.85
20,Italy,1.39,1.83,2.71,3.37,4.22,4.67,5.11,5.26,5.97,...,12.49,17.08,18.72,19.39,19.50,19.37,19.14,19.55,19.58,19.83
21,Latvia,0.00,0.00,0.01,0.02,0.04,0.04,0.04,0.04,0.04,...,0.29,0.50,0.67,0.77,0.82,0.93,0.94,0.93,0.87,0.86
22,Lithuania,0.00,0.00,0.00,0.01,0.01,0.01,0.02,0.05,0.07,...,0.22,0.36,0.40,0.45,0.44,0.50,0.54,0.53,0.52,0.51
23,Luxembourg,0.02,0.03,0.03,0.03,0.04,0.05,0.06,0.06,0.07,...,0.09,0.09,0.12,0.13,0.14,0.17,0.22,0.28,0.36,0.38
24,Malta,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
25,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.01,0.01,0.01,0.02,0.03,0.03,NaN,NaN
26,Montenegro,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
27,Netherlands,1.99,2.35,2.90,2.54,3.31,5.26,5.17,4.00,5.13,...,7.20,5.95,5.01,4.92,4.90,4.60,4.57,5.81,8.65,11.65
28,North Macedonia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.02,0.04,0.05,0.05,0.06,0.06,0.06
29,Norway,0.26,0.25,0.25,0.33,0.36,0.33,0.39,0.39,0.40,...,0.33,0.40,0.26,0.26,0.23,0.26,0.20,0.25,0.25,0.25
30,Poland,0.22,0.44,0.43,0.46,0.98,1.51,1.99,2.56,3.62,...,10.09,8.62,9.98,9.94,7.96,6.49,6.55,7.68,7.70,7.53
31,Portugal,1.30,1.35,1.47,1.39,1.54,1.68,1.70,1.86,1.85,...,2.95,3.05,3.05,3.10,3.07,3.22,3.16,3.36,3.91,3.92
32,Romania,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.04,0.02,...,0.21,0.25,0.50,0.52,0.53,0.53,0.44,0.50,0.58,0.65
33,Serbia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.01,0.02,0.02,0.02,0.03,0.08,0.10,0.14,0.16,0.28
34,Slovakia,0.00,0.15,0.15,0.10,0.02,0.03,0.40,0.47,0.52,...,0.94,0.91,1.42,1.66,1.73,1.70,1.63,1.69,1.77,1.76
35,Slovenia,0.07,0.07,0.10,0.12,0.12,0.11,0.11,0.11,0.29,...,0.27,0.26,0.25,0.26,0.28,0.28,0.26,0.25,0.26,0.20
36,Spain,1.49,1.63,2.59,3.18,3.33,2.65,2.77,2.90,3.26,...,4.98,5.80,5.41,5.76,5.69,6.08,5.91,5.57,6.49,6.80
37,Sweden,4.10,3.78,4.18,4.51,7.20,7.49,8.36,9.84,10.34,...,12.19,11.45,10.70,10.77,11.49,12.08,11.91,13.04,10.84,12.99
38,Turkey,0.17,0.18,0.13,0.08,0.08,0.03,0.06,0.09,0.14,...,0.59,0.88,1.08,1.24,1.63,2.10,2.65,3.51,4.42,6.26
39,Ukraine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.26,...,0.13,0.10,0.13,0.14,0.14,0.21,0.30,0.41,NaN,NaN
40,United Kingdom,3.94,4.53,5.08,6.10,7.36,9.10,9.28,9.33,9.57,...,14.73,18.10,22.62,28.47,30.06,31.87,34.93,37.29,38.10,39.10

In [218]:
df.sort_values('2000')

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Albania,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
28,North Macedonia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.02,0.04,0.05,0.05,0.06,0.06,0.06
24,Malta,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
22,Lithuania,0.00,0.00,0.00,0.01,0.01,0.01,0.02,0.05,0.07,...,0.22,0.36,0.40,0.45,0.44,0.50,0.54,0.53,0.52,0.51
21,Latvia,0.00,0.00,0.01,0.02,0.04,0.04,0.04,0.04,0.04,...,0.29,0.50,0.67,0.77,0.82,0.93,0.94,0.93,0.87,0.86
39,Ukraine,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.26,...,0.13,0.10,0.13,0.14,0.14,0.21,0.30,0.41,NaN,NaN
18,Iceland,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
16,Greece,0.00,0.08,0.13,0.10,0.12,0.12,0.11,0.18,0.19,...,0.20,0.22,0.22,0.23,0.27,0.31,0.31,0.40,0.40,0.40
33,Serbia,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.01,0.02,0.02,0.02,0.03,0.08,0.10,0.14,0.16,0.28
34,Slovakia,0.00,0.15,0.15,0.10,0.02,0.03,0.40,0.47,0.52,...,0.94,0.91,1.42,1.66,1.73,1.70,1.63,1.69,1.77,1.76
32,Romania,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.04,0.02,...,0.21,0.25,0.50,0.52,0.53,0.53,0.44,0.50,0.58,0.65
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
11,Estonia,0.01,0.01,0.02,0.03,0.03,0.04,0.04,0.03,0.04,...,1.00,0.67,0.76,0.82,0.95,1.10,1.31,1.36,1.35,1.25
23,Luxembourg,0.02,0.03,0.03,0.03,0.04,0.05,0.06,0.06,0.07,...,0.09,0.09,0.12,0.13,0.14,0.17,0.22,0.28,0.36,0.38
17,Hungary,0.06,0.07,0.04,0.16,0.73,1.66,1.26,1.56,1.94,...,1.65,1.83,2.13,2.16,2.07,2.15,2.30,2.22,2.27,2.37
35,Slovenia,0.07,0.07,0.10,0.12,0.12,0.11,0.11,0.11,0.29,...,0.27,0.26,0.25,0.26,0.28,0.28,0.26,0.25,0.26,0.20
19,Ireland,0.09,0.10,0.08,0.09,0.11,0.13,0.13,0.18,0.22,...,0.44,0.49,0.54,0.48,0.68,0.74,0.85,0.85,0.85,0.85
38,Turkey,0.17,0.18,0.13,0.08,0.08,0.03,0.06,0.09,0.14,...,0.59,0.88,1.08,1.24,1.63,2.10,2.65,3.51,4.42,6.26
30,Poland,0.22,0.44,0.43,0.46,0.98,1.51,1.99,2.56,3.62,...,10.09,8.62,9.98,9.94,7.96,6.49,6.55,7.68,7.70,7.53
29,Norway,0.26,0.25,0.25,0.33,0.36,0.33,0.39,0.39,0.40,...,0.33,0.40,0.26,0.26,0.23,0.26,0.20,0.25,0.25,0.25
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
31,Portugal,1.30,1.35,1.47,1.39,1.54,1.68,1.70,1.86,1.85,...,2.95,3.05,3.05,3.10,3.07,3.22,3.16,3.36,3.91,3.92
20,Italy,1.39,1.83,2.71,3.37,4.22,4.67,5.11,5.26,5.97,...,12.49,17.08,18.72,19.39,19.50,19.37,19.14,19.55,19.58,19.83
36,Spain,1.49,1.63,2.59,3.18,3.33,2.65,2.77,2.90,3.26,...,4.98,5.80,5.41,5.76,5.69,6.08,5.91,5.57,6.49,6.80
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
27,Netherlands,1.99,2.35,2.90,2.54,3.31,5.26,5.17,4.00,5.13,...,7.20,5.95,5.01,4.92,4.90,4.60,4.57,5.81,8.65,11.65
13,France,2.48,2.85,3.04,3.23,3.31,3.39,3.38,3.75,3.97,...,5.30,5.68,5.99,6.53,7.52,7.78,8.38,8.64,8.47,8.67
40,United Kingdom,3.94,4.53,5.08,6.10,7.36,9.10,9.28,9.33,9.57,...,14.73,18.10,22.62,28.47,30.06,31.87,34.93,37.29,38.10,39.10
37,Sweden,4.10,3.78,4.18,4.51,7.20,7.49,8.36,9.84,10.34,...,12.19,11.45,10.70,10.77,11.49,12.08,11.91,13.04,10.84,12.99
15,Germany,4.33,4.59,5.31,8.95,10.64,14.71,18.94,24.62,28.02,...,43.20,45.51,48.29,50.33,50.93,50.92,50.90,50.22,49.27,48.99
12,Finland,8.64,8.27,8.99,9.38,10.44,9.51,10.81,9.95,10.40,...,11.20,12.01,11.76,11.42,11.52,11.86,12.91,13.29,11.08,12.28
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01
14,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
25,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,0.01,0.01,0.01,0.02,0.03,0.03,NaN,NaN
26,Montenegro,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [219]:
# Comparasing only data for first 10 examples
first_10=df.head(10)
first_10

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Albania,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.01,0.01,0.01,0.01,0.01
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60

In [220]:
first_10_NAN = first_10[first_10.isna().any(axis=1)]

In [221]:
first_10_NAN

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,NaN,NaN
4,Bosnia Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.01,0.01,0.01,0.01,0.01

In [222]:
first_10_NONAN = first_10[first_10.notnull().all(axis=1)]

In [223]:
first_10_NONAN

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
2,Austria,1.53,1.67,1.52,1.65,1.91,2.43,3.23,4.06,4.16,...,4.68,4.70,4.55,4.65,4.78,4.92,4.93,4.75,4.29,4.03
3,Belgium,0.57,0.60,0.72,0.86,1.04,1.59,2.23,2.60,3.33,...,5.24,5.03,4.46,5.55,5.44,5.77,5.46,5.23,5.24,5.05
5,Bulgaria,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,...,0.07,0.11,0.20,0.27,0.35,0.40,1.57,1.82,1.83,1.82
6,Croatia,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,...,0.09,0.13,0.16,0.27,0.43,0.53,0.67,0.88,0.94,1.04
7,Cyprus,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,...,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06
8,Czechia,0.52,0.52,0.50,0.49,0.71,0.73,0.92,1.20,1.45,...,3.37,4.06,4.66,4.79,4.76,4.97,4.83,5.03,5.41,5.58
9,Denmark,1.30,1.51,1.88,2.49,2.91,3.17,3.07,3.10,3.14,...,4.45,4.31,4.29,4.18,4.85,6.25,5.89,5.95,5.30,7.12
10,EU-27,30.11,31.90,36.80,43.16,52.76,61.00,69.86,78.43,88.09,...,132.87,139.13,144.30,149.41,151.16,153.71,155.65,159.90,158.30,166.60

Now from 10 rows we've got only 8 with value for every year

In [240]:
first_10_NONAN['2000'].sort_index

<bound method Series.sort_index of 2      1.53
3      0.57
5      0.00
6      0.00
7      0.00
8      0.52
9      1.30
10    30.11
Name: 2000, dtype: float64>

In [241]:
to_analyze=first_10_NONAN['2000']

In [226]:
first_10_NONAN.iloc[1]

Country    Belgium
2000          0.57
2001           0.6
2002          0.72
2003          0.86
2004          1.04
2005          1.59
2006          2.23
2007           2.6
2008          3.33
2009          3.95
2010          4.38
2011          4.63
2012          5.24
2013          5.03
2014          4.46
2015          5.55
2016          5.44
2017          5.77
2018          5.46
2019          5.23
2020          5.24
2021          5.05
Name: 3, dtype: object

In [242]:
table= first_10_NONAN.iloc[1:,0:7]

In [243]:
table.sort_values

<bound method DataFrame.sort_values of      Country   2000   2001   2002   2003   2004   2005
3    Belgium   0.57   0.60   0.72   0.86   1.04   1.59
5   Bulgaria   0.00   0.00   0.00   0.00   0.00   0.00
6    Croatia   0.00   0.00   0.00   0.00   0.00   0.01
7     Cyprus   0.00   0.00   0.00   0.00   0.00   0.00
8    Czechia   0.52   0.52   0.50   0.49   0.71   0.73
9    Denmark   1.30   1.51   1.88   2.49   2.91   3.17
10     EU-27  30.11  31.90  36.80  43.16  52.76  61.00>

In [244]:
table.aggregate(['max'])

    Country   2000  2001  2002   2003   2004  2005
max   EU-27  30.11  31.9  36.8  43.16  52.76  61.0

In [245]:
table.aggregate(['mean'])

          2000      2001  2002      2003      2004  2005
mean  4.642857  4.932857   5.7  6.714286  8.202857   9.5

In [250]:
table.aggregate(['sum'])

,Country,2000,2001,2002,2003,2004,2005
sum,BelgiumBulgariaCroatiaCyprusCzechiaDenmarkEU-27,32.5,34.53,39.9,47.0,57.42,66.5